name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go test -race -v ./...

    - name: Install
      run: go install .

    - name: Generate Code
      run: |
        chmod +x ./script/gen_test.sh
        ./script/gen_test.sh
